// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXWDfrKMkYf3ntTBZjipJmqtcdSwZv5Kc',
    appId: '1:205448568564:web:e9ea825555713e135e88a1',
    messagingSenderId: '205448568564',
    projectId: 'simple-todolist-d9180',
    authDomain: 'simple-todolist-d9180.firebaseapp.com',
    storageBucket: 'simple-todolist-d9180.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfcweUxsKRiXPJzrpP4ikUTVLw7LaEk8o',
    appId: '1:205448568564:android:414186f1c94736b25e88a1',
    messagingSenderId: '205448568564',
    projectId: 'simple-todolist-d9180',
    storageBucket: 'simple-todolist-d9180.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_3Zh-_dE_gZuCoqBOEAzy7QjBhz1juOM',
    appId: '1:205448568564:ios:e1ba76e29cc6260a5e88a1',
    messagingSenderId: '205448568564',
    projectId: 'simple-todolist-d9180',
    storageBucket: 'simple-todolist-d9180.appspot.com',
    iosClientId: '205448568564-l629rg7h4ilneoiuh923tdpd51455gta.apps.googleusercontent.com',
    iosBundleId: 'com.example.simpleTodolist',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_3Zh-_dE_gZuCoqBOEAzy7QjBhz1juOM',
    appId: '1:205448568564:ios:e1ba76e29cc6260a5e88a1',
    messagingSenderId: '205448568564',
    projectId: 'simple-todolist-d9180',
    storageBucket: 'simple-todolist-d9180.appspot.com',
    iosClientId: '205448568564-l629rg7h4ilneoiuh923tdpd51455gta.apps.googleusercontent.com',
    iosBundleId: 'com.example.simpleTodolist',
  );
}
